### ISSUE TITLE
Alphabetically sort listings by name

### ISSUE THREAD

**Issue by hugeblank** [Ale32bit/ShopIndex#1]
This applies to:
[ ] Catalogue
[ ] Shops
[ ] Shop Items

I figure until more advanced item/shop searching is implemented having them in alphabetical order will be sufficient.

**Comment by Ale32bit** [comment]
Added in 6ece4bd939c841645678d7525e653230372e52aa, 06d685a8d3b6ba2599260481389f0f1b08d63307 and 55e881096c6d2b98a74cd812e9d1a67f86246247
