### ISSUE TITLE
Relocate "Details" button to the entire box (or just shop name) 

### ISSUE THREAD

**Issue by hugeblank** [Ale32bit/ShopIndex#2]
![image](https://github.com/Ale32bit/ShopIndex/assets/16393543/06a0769f-8915-4e82-9f51-99e29e1b3be6)
Instead of having a details button, either the entire box or just the shop title could be made clickable.

Side note, making the boxes all the same size regardless of whether there's a description would be nice.
![image](https://github.com/Ale32bit/ShopIndex/assets/16393543/b024cd12-515f-4345-8b21-b34813613611)

**Comment by Ale32bit** [comment]
Done in a00569b5552475a16d2ef9f637ecca2cb246f539
